Repository furkanpasaoglu/TaskBoardManagementApp, pull requests merged in 2022-10, with the labels that each got.

#6 login error fixed
  TaskBoardManagementApp/src/WebUI/Program.cs
Labels: bug

#9 Created Issue Detail
  .idea/.idea.TaskBoardManagementApp/.idea/.gitignore
  .idea/.idea.TaskBoardManagementApp/.idea/encodings.xml
  .idea/.idea.TaskBoardManagementApp/.idea/indexLayout.xml
  .idea/.idea.TaskBoardManagementApp/.idea/vcs.xml
  .idea/config/applicationhost.config
  TaskBoardManagementApp/src/Application/Application.csproj
  TaskBoardManagementApp/src/Application/ConfigureServices.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/CreateIssueDetail/CreateIssueDetailCommand.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/CreateIssueDetail/CreateIssueDetailCommandValidator.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/DeleteIssueDetail/DeleteIssueDetailCommand.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/DeleteIssueDetail/DeleteIssueDetailCommandValidator.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/UpdateIssueDetail/UpdateIssueDetailCommand.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Commands/UpdateIssueDetail/UpdateIssueDetailCommandValidator.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Constants/IssueDetailMessages.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Dtos/CreatedIssueDetailDto.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Dtos/DeletedIssueDetailDto.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Dtos/IssueDetailGetByIdDto.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Dtos/IssueDetailListDto.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Dtos/UpdatedIssueDetailDto.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Profiles/MappingProfiles.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Queries/GetByIdIssueDetail/GetByIdIssueDetailQuery.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Queries/GetByIdIssueDetail/GetByIdIssueDetailQueryValidator.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Queries/GetListIssueDetail/GetListIssueDetailQuery.cs
  TaskBoardManagementApp/src/Application/IssueDetails/Rules/IssueDetailBusinessRules.cs
  TaskBoardManagementApp/src/Application/Issues/Commands/CreateIssue/CreateIssueCommand.cs
  TaskBoardManagementApp/src/Application/Issues/Commands/CreateIssue/CreateIssueCommandValidator.cs
  TaskBoardManagementApp/src/Application/Issues/Commands/DeleteIssue/DeleteIssueCommandValidator.cs
  TaskBoardManagementApp/src/Application/Issues/Commands/UpdateIssue/UpdateIssueCommand.cs
  TaskBoardManagementApp/src/Application/Issues/Constants/IssueMessages.cs
  TaskBoardManagementApp/src/Application/Issues/Dtos/CreatedIssueDto.cs
  TaskBoardManagementApp/src/Application/Issues/Dtos/DeletedIssueDto.cs
  TaskBoardManagementApp/src/Application/Issues/Dtos/IssueGetByIdDto.cs
  TaskBoardManagementApp/src/Application/Issues/Dtos/IssueListDto.cs
  TaskBoardManagementApp/src/Application/Issues/Dtos/UpdatedIssueDto.cs
  TaskBoardManagementApp/src/Application/Issues/EventHandlers/IssueCreatedEventHandler.cs
  TaskBoardManagementApp/src/Application/Issues/Profiles/MappingProfiles.cs
  TaskBoardManagementApp/src/Application/Issues/Queries/GetByIdIssue/GetByIdIssueQuery.cs
  TaskBoardManagementApp/src/Application/Issues/Queries/GetByIdIssue/GetByIdIssueQueryValidator.cs
  TaskBoardManagementApp/src/Application/Issues/Queries/GetListIssues/GetListIssueQuery.cs
  TaskBoardManagementApp/src/Application/Issues/Rules/IssueBusinessRules.cs
  TaskBoardManagementApp/src/WebUI/ClientApp/src/app/web-api-client.ts
  TaskBoardManagementApp/src/WebUI/Controllers/IssueDetailsController.cs
  TaskBoardManagementApp/src/WebUI/Controllers/IssuesController.cs
  TaskBoardManagementApp/src/WebUI/Program.cs
  TaskBoardManagementApp/src/WebUI/wwwroot/api/specification.json
Labels: review

#11 Create README.md
  README.md
Labels: documentation

#13 WorkLog Entity Created
  .idea/.idea.TaskBoardManagementApp/.idea/dataSources.xml
  .idea/.idea.TaskBoardManagementApp/.idea/efCoreCommonOptions.xml
  TaskBoardManagementApp/src/Application/Application.csproj
  TaskBoardManagementApp/src/Application/ConfigureServices.cs
  TaskBoardManagementApp/src/Application/Features/Comments/Commands/CreateComment/CreateCommentCommand.cs
  TaskBoardManagementApp/src/Application/Features/IssueDetails/Commands/CreateIssueDetail/CreateIssueDetailCommand.cs
  TaskBoardManagementApp/src/Application/Features/IssueDetails/Commands/UpdateIssueDetail/UpdateIssueDetailCommand.cs
  TaskBoardManagementApp/src/Application/Features/Issues/Queries/GetListIssue/GetListIssueQuery.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/CreateWorkLog/CreateWorkLogCommand.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/CreateWorkLog/CreateWorkLogCommandValidator.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/DeleteWorkLog/DeleteWorkLogCommand.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/DeleteWorkLog/DeleteWorkLogCommandValidator.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/UpdateWorkLog/UpdateWorkLogCommand.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Commands/UpdateWorkLog/UpdateWorkLogCommandValidator.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Constants/WorkLogMessages.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Dtos/CreatedWorkLogDto.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Dtos/DeletedWorkLogDto.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Dtos/UpdatedWorkLogDto.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Dtos/WorkLogGetByIdDto.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Dtos/WorkLogListDto.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Profiles/MappingProfiles.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Queries/GetByIdWorkLog/GetByIdWorkLogQuery.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Queries/GetByIdWorkLog/GetByIdWorkLogQueryValidator.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Queries/GetListWorkLog/GetListWorkLogQuery.cs
  TaskBoardManagementApp/src/Application/Features/WorkLogs/Rules/WorkLogBusinessRules.cs
  TaskBoardManagementApp/src/WebUI/ClientApp/src/app/web-api-client.ts
  TaskBoardManagementApp/src/WebUI/Controllers/IssuesController.cs
  TaskBoardManagementApp/src/WebUI/Controllers/WorkLogsController.cs
  TaskBoardManagementApp/src/WebUI/wwwroot/api/specification.json
Labels: review

#14 Create README.md
  README.md
Labels: review
